
#pragma once
namespace pandemic
{
    enum class City
    {
      Algiers,
        Madrid,
        Paris,
        Istanbul,
        Cairo,
        Atlanta,
        Chicago,
        Miami,
        Washington,
        Baghdad,
        Tehran,
        Riyadh,
        Karachi,
        Bangkok,
        Kolkata,
        Chennai,
        Jakarta,
        HoChiMinhCity,
        HongKong,
        Beijing,
        Shanghai,
        Seoul,
        Bogota,
        MexicoCity,
        Lima,
        SaoPaulo,
        BuenosAires,
        Khartoum,
        Mumbai,
        Delhi,
        SanFrancisco,
        LosAngeles,
        Montreal,
        Essen,
        London,
        Milan,
        StPetersburg,
        Manila,
        Taipei,
        Moscow,
        Sydney,
        Johannesburg,
        Kinshasa,
        Lagos,
        NewYork,
        Osaka,
        Santiago,
        Tokyo
    };

}
